version: "3"
name: "securawatch"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        restart: always
        networks:
            - securawatch
        env_file:
            - ./backend/.env
        ports:
            - "8000:8000"

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        restart: always
        networks:
            - securawatch
        ports:
            - "3000:3000"
        depends_on:
            - backend

networks:
    securawatch:
        name: securawatch
