def isIntrusion(class_name: str, intrusion_type: str):
    return class_name == intrusion_type


def isWeapon(class_name: str):
    return class_name in [
        "knife",
        "gun",
        "rifle",
        "sword",
        "dagger",
        "scissors",
        "hammer",
        "axe",
        "spear",
        "machete",
        "baton",
        "bow",
        "crossbow",
        "blowgun",
        "cannon",
        "flamethrower",
        "grenade",
        "landmine",
        "missile",
        "rocket",
        "torpedo",
        "bomb",
        "explosive",
        "firearm",
        "ammunition",
        "bullet",
        "shell",
        "cartridge",
        "projectile",
        "arrow",
        "bolt",
        "dart",
        "slingshot",
        "sling",
        "whip",
        "lasso",
        "noose",
        "trap",
        "snare",
        "net",
    ]
